#timeseries CLCT out02
#timeseries FR_LAND out02
#timeseries PMSL out02
#timeseries QV_2M out02
#timeseries TMAX_2M out02
#timeseries TOT_PREC out02
#timeseries AEVAP_S out02
#timeseries HSURF out02
#timeseries PS out02
#timeseries RELHUM_2M out02
#timeseries T_2M out02
#timeseries TMIN_2M out02
#timeseries ASWD_S out02
#timeseries ATHD_S out02
##timeseries U_10M out02
timeseries SP_10M out02
#timeseries V_10M out02
#timeseries ATHB_S out02
#timeseries ATHU_S out02
#timeseries ATHD_S out02
#timeseries ASODIFD_S out02
#timeseries ASODIR_S out02
#timeseries ASWD_S out02

